version: '3.8'

services:
  php-web:
    image: php:8.2-apache
    ports:
      - "8082:80"
    volumes:
      - ./php/public:/var/www/html
      - ./php/scripts-php:/var/www/scripts 
    networks:
      - php-network
    command: >
     bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aula_db
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - php-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - php-network

volumes:
  mysql-data:


networks:
  php-network:

composer:
  image: composer:2
  volumes:
  - .laravel:/app
  networks:
  - php.network